[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.3.19"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
categories = ["game-engines"]
homepage = "https://ryanisaacg.github.io/quicksilver"
keywords = ["game", "audio", "graphics", "gamedev"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ryanisaacg/quicksilver"
exclude = ["docs/*"]
edition = "2018"

[features]
# complex_shapes, fonts, gamepads, sounds
default = ["saving"]

# complex_shapes = ["lyon"]
# fonts = ["rusttype"]
# gamepads = ["gilrs"]
saving = ["gestalt"]
# sounds = ["rodio"]
stdweb = ["gestalt/stdweb", "platter/stdweb", "blinds/stdweb"]
web-sys = ["gestalt/web-sys", "platter/web-sys", "blinds/web-sys"]

[badges]

travis-ci = { repository = "ryanisaacg/quicksilver", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
gestalt = { version = "0.1", optional = true }
glow = "0.3.0-alpha3"
image = "0.21"
mint = "0.5.3"
platter = "0.1"
blinds = { git = "https://github.com/ryanisaacg/blinds" }

[[example]]
name = "draw-geometry"
required-features = []

[[example]]
name = "image"
required-features = []

[[example]]
name = "font"
required-features = ["fonts"]

[[example]]
name = "sound"
required-features = ["sounds"]

[[example]]
name = "raycast"
required-features = ["collisions"]

[[example]]
name = "rgb-triangle"
required-features = []

[[example]]
name = "lyon"
required-features = ["complex_shapes"]

[[example]]
name = "set-cursor"
required-features = []

[[example]]
name = "stopwatch"
required-features = []

[[example]]
name = "camera"
required-features = []

